# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: id_graph
    model_type: id_stitcher
    model_spec:
      entity_key: shopify_customer
      materialization:
        run_type: discrete
      validity_time: 24h
      edge_sources:
        - from: inputs/CART_UPDATE
        - from: inputs/CHECKOUT_UPDATED
        - from: inputs/IDENTIFIES
        - from: inputs/ORDER_CREATED
        - from: inputs/ORDER_PAID
        - from: inputs/TRACKS
        - from: inputs/PAGES
        - from: inputs/CHECKOUT_STARTED
        - from: inputs/ORDER_UPDATED
        - from: inputs/PRODUCT_CLICKED
        - from: inputs/PRODUCT_LIST_VIEWED
        - from: inputs/USERS
        - from: inputs/PRODUCT_ADDED
        - from: inputs/PRODUCT_VIEWED

  - name: user_profile
    model_type: feature_table_model
    model_spec:
      entity_key: shopify_customer
      validity_time: 24h
      compatibility_mode:
        linear_dependency_of_vars: false
      features:
        - first_name
var_groups:
  - name: shopify_users_vars
    entity_key: shopify_customer
    vars:
      - entity_var:
          select: first_value(first_name)
          name: first_name
          window:
            order_by:
              - timestamp desc
          from: inputs/IDENTIFIES
          where: first_name is not null and first_name!=''
      - entity_var:
          select: first_value(last_name)
          name: last_name
          window:
            order_by:
              - timestamp desc
          from: inputs/IDENTIFIES
          where: last_name is not null and last_name!=''
## why do you have to apply a window function here?
## - pulled feature from here: https://github.com/rudderlabs/profiles-shopify-features/blob/main/models/profiles.yaml